In [1]:
import numpy as np
from scipy.spatial.transform import Rotation as R

# === Step 1: 定义欧拉角 ===
yaw, pitch, roll = 30, 20, 10  # 单位：度
yaw, pitch, roll = np.radians([yaw, pitch, roll])

# === Step 2: 手动构造每个轴的旋转矩阵 ===
def rot_z(theta):
    return np.array([
        [np.cos(theta), -np.sin(theta), 0],
        [np.sin(theta),  np.cos(theta), 0],
        [0,              0,             1]
    ])

def rot_y(theta):
    return np.array([
        [np.cos(theta),  0, np.sin(theta)],
        [0,              1, 0],
        [-np.sin(theta), 0, np.cos(theta)]
    ])

def rot_x(theta):
    return np.array([
        [1, 0,              0],
        [0, np.cos(theta), -np.sin(theta)],
        [0, np.sin(theta),  np.cos(theta)]
    ])

# === Step 3: 按照内旋顺序组合 ===
# 内旋：依次绕当前坐标系的 ZYX 轴 → 对应矩阵乘法 R = R_x * R_y * R_z（从右往左）
R_manual = rot_x(roll) @ rot_y(pitch) @ rot_z(yaw)

# === Step 4: 使用 scipy 验证内旋一致性 ===
R_scipy = R.from_euler('zyx', [30, 20, 10], degrees=True).as_matrix()

# === Step 5: 比较 ===
print("是否一致：", np.allclose(R_manual, R_scipy, atol=1e-8))
print("手动构造 R：\n", R_manual)
print("scipy R：\n", R_scipy)


是否一致： True
手动构造 R：
 [[ 0.81379768 -0.46984631  0.34202014]
 [ 0.54383814  0.82317294 -0.16317591]
 [-0.20487413  0.31879578  0.92541658]]
scipy R：
 [[ 0.81379768 -0.46984631  0.34202014]
 [ 0.54383814  0.82317294 -0.16317591]
 [-0.20487413  0.31879578  0.92541658]]
